export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL"

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL"

export const CART_ADD_REQUEST = "CART_ADD_REQUEST"
export const CART_ADD_SUCCESS = "CART_ADD_SUCCESS"
export const CART_ADD_FAIL = "CART_ADD_FAIL"

export const CART_REMOVE_REQUEST = "CART_REMOVE_REQUEST"
export const CART_REMOVE_SUCCESS = "CART_REMOVE_SUCCESS"
export const CART_REMOVE_FAIL = "CART_REMOVE_FAIL"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"

export const SIGNUP_REQUEST = "SIGNUP_REQUEST"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAIL = "SIGNUP_FAIL"

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS"
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL"

export const PROFILE_UPDATE_REQUEST = "PROFILE_UPDATE_REQUEST"
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS"
export const PROFILE_UPDATE_FAIL = "PROFILE_UPDATE_FAIL"

export const SHIPPING_ADDRESS_REQUEST = "SHIPPING_ADDRESS_REQUEST"
export const SHIPPING_ADDRESS_SUCCESS = "SHIPPING_ADDRESS_SUCCESS"
export const SHIPPING_ADDRESS_FAIL = "SHIPPING_ADDRESS_FAIL"

export const PAYMENT_METHOD_REQUEST = "PAYMENT_METHOD_REQUEST"
export const PAYMENT_METHOD_SUCCESS = "PAYMENT_METHODSS_SUCCESS"
export const PAYMENT_METHOD_FAIL = "PAYMENT_METHOD_FAIL"
