export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DEAILS_REQUEST = "PRODUCT_DEAILS_REQUEST";
export const PRODUCT_DEAILS_SUCCESS = "PRODUCT_DEAILS_SUCCESS";
export const PRODUCT_DEAILS_FAIL = "PRODUCT_DEAILS_FAIL";
